server:
  port: ${GATEWAY_PORT:4040}

spring:
  application:
    name: database-server
  datasource:
    platform: postgres
    url: ${POSTGRESQL_URL:jdbc:postgresql://localhost:5432/${PRODUCT_DATABASE:store}}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/liquibase-changelog.yml
    default-schema: purchase_management


