version: "3"

services:

### SQL DATABASE ###
  storedb:
    build: ./initial-database-tools
    network_mode: bridge
    container_name: postgres
    expose:
      - 5432
    ports:
      - 5431:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_STANDARD_PASSWORD:password}
      - POSTGRES_USER=${POSTGRES_STANDARD_USER:postgres}
      - POSTGRES_DB=store
    restart: on-failure

### MONGODB DATABASE ###
  productdb:
    image: mongo
    network_mode: bridge
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongodb
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    restart: on-failure

### RABBIQ MQ ###
  rabbiqmq:
    image: rabbitmq
    network_mode: bridge
    container_name: rabbitmq
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672