version: "3"

volumes:
  elastic01:
    driver: local

networks:
  elk:
    driver: bridge
  database:
    driver: bridge

services:

### SQL DATABASE ###
  storedb:
    build: ./initial-database-tools
    container_name: postgres
    expose:
      - 5432
    ports:
      - 5431:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_STANDARD_PASSWORD:password}
      - POSTGRES_USER=${POSTGRES_STANDARD_USER:postgres}
      - POSTGRES_DB=store
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 300M
        reservations:
          cpus: '1'
          memory: 100M

### MONGODB DATABASE ###
  productdb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_ADMIN_USERNAME:mongodb}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_ADMIN_PASSWORD:password}
    restart: on-failure

### RABBIQ MQ ###
  rabbiqmq:
    image: rabbitmq
    container_name: rabbitmq
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672
    restart: on-failure

### ELK STACK ###
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.6.2
    restart: unless-stopped
    networks:
      - elk
    ports:
      - 5601:5601
    expose:
      - 5601
    depends_on:
      - elastic01
      - elastic02
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro # Добавить конфиг
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.5'
          memory: 250M

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.6.2
    environment:
      XPACK_MONITORING_ENABLED: "false"
    networks:
      - elk
    ports:
      - 5046:5046
    volumes:
      - ./config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./config/pipelines:/usr/share/logstash/config/pipelines:ro
      - ./logs:/usr/share/logstash/input

  elastic01:
    container_name: elasticsearch01
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    restart: unless-stopped
    networks:
      - elk
    volumes:
      - ./data01:/usr/share/elasticsearch/data
    environment:
      - node.name=elastic01
      - cluster.initial_master_nodes=elastic01,elastic02
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=false
      - discovery.seed_hosts=elastic02
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.5'
          memory: 250M

  elastic02:
    container_name: elasticsearch02
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    restart: unless-stopped
    networks:
      - elk
    environment:
      - node.name=elastic02
      - cluster.initial_master_nodes=elastic01,elastic02
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=false
      - discovery.seed_hosts=elastic01
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.5'
          memory: 250M
